main: com.smp.core.Main
name: SMP
version: 2.3
author: Michele
api-version: 1.16

commands:
  gmc:
    description: Changes user to creative (ONLY IF THE PLAYER IS NOT IN CREATIVE)
  gm:
    description: Changes user gamemode based on triggers.
  fly:
    description: Toggles fly on-off.
  heal:
    description: Heals player.
  feed:
    description: Feeds player.
  clearchat:
    description: Clears chat.
  getpos:
    description: Sends players coordinates.
  broadcast:
    description: Broadcasts input.
  nick:
    description: Nicknames player.
  teleport:
    description: Teleports a target player to somone else.
    aliases: [tp]
  msg:
    description: Private messages.
  kill:
    description: Kills player if no arguments.
  tpbow:
    description: Gives player teleport bow.
  gui:
    description: Opens a GUI.
  god:
    description: Makes the player God.
  vanish:
    description: Vanishes the player.